name: Selenium Scrape

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports: 
          - 4445:4444
        options: --shm-size="2g"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.1.0'

    - name: Install RSelenium
      run: Rscript -e 'install.packages("RSelenium", repos = "http://cran.rstudio.com/")'

    - name: Run R Script to Scrape HTML Pages
      run: Rscript scripts/test_selenium.R
      env:
        SELENIUM_BROWSER: firefox
        SELENIUM_REMOTE_URL: "http://selenium:4445/wd/hub"
